# Generated by Django 5.0.6 on 2024-06-09 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Users Model', 'verbose_name_plural': 'Custom User'},
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together={('username', 'email')},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='Django Form Table',
        ),
        migrations.CreateModel(
            name='categorymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=100, null=True)),
                ('create_at', models.DateField(auto_now_add=True, null=True)),
                ('update_at', models.DateField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priotiry', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=100, null=True)),
                ('taskname', models.CharField(max_length=100, null=True)),
                ('due_date', models.DateField(null=True)),
                ('date', models.DateField(null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('status', models.CharField(default='On_Going', max_length=100, null=True)),
                ('create_at', models.DateField(auto_now_add=True, null=True)),
                ('update_at', models.DateField(auto_now=True, null=True)),
                ('completed_date', models.DateField(null=True)),
                ('categorytast', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.categorymodel')),
            ],
        ),
    ]
