# Generated by Django 5.0.6 on 2024-06-10 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'ordering': ['categoryname'], 'verbose_name': 'Category Model'},
        ),
        migrations.AlterUniqueTogether(
            name='categorymodel',
            unique_together={('categoryname',)},
        ),
        migrations.AlterModelTable(
            name='categorymodel',
            table='Category Table',
        ),
    ]
