# Generated by Django 5.0.6 on 2024-06-10 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_categorymodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
